name: cash_flow
description: The best investment trainer!
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.22.6
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+1
  intl: ^0.16.1

  built_value: ^7.0.8
  built_collection: ^4.3.0

  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.4+2

  json_serializable: ^3.2.5

  flutter_platform_core:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-platform-core
      ref: v0.0.13

  flutter_platform_network:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter_platform_network
      ref: v0.0.12

  flutter_platform_control_panel:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-platform-control-panel
      ref: v0.0.6

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^7.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
