name: cash_flow
description: The best investment trainer!
version: 2.1.0+44

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  rxdart: ^0.24.1
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+1
  intl: ^0.16.1
  crypto: ^2.1.5
  get_it: ^5.0.1
  json_serializable: ^3.2.5
  device_preview: ^0.4.4
  in_app_purchase: ^0.3.3
  connectivity: ^2.0.0
  fimber: ^0.4.4
  flutter_rollbar: ^0.0.2

  # Test
  mockito: ^4.1.2
  test: ^1.15.4

  # Immutability
  built_value: ^7.1.0
  built_collection: ^4.3.2
  freezed_annotation: ^0.11.0+1

  # Firebase
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.0
  firebase_dynamic_links: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_performance: ^0.5.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0
  firebase_remote_config: ^0.6.0

  # Analytics
  amplitude_flutter: ^2.0.0

  # Notifications
  notification_permissions: ^0.4.8

  # Social
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0

  # Images
  image_picker: ^0.6.7+21
  image_cropper: ^1.3.1

  # UI
  flutter_hooks: ^0.12.0
  auto_size_text: ^2.1.0
  tutorial_coach_mark: ^0.5.1
  cached_network_image: ^2.3.3
  smooth_page_indicator: ^0.2.0
  flutter_svg: ^0.18.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.2
  share: ^0.6.5+4
  flutter_swiper: ^1.1.6
  shimmer: ^1.1.2
  app_settings: ^4.0.4
  percent_indicator: ^2.1.7+2
  feedback: ^0.2.1+1
  k_chart:
    git:
      url: https://github.com/robertBadamshin/k_chart
      ref: chart-design-updates

  # Dash Kit
  dash_kit_core: ^2.1.2
  dash_kit_network: ^2.0.4
  dash_kit_control_panel: ^1.0.0
  dash_kit_loadable: ^2.1.2
  dash_kit_uikit: ^1.0.0

  google_mobile_ads: ^0.11.0

  version: ^1.3.0
  launch_review: ^2.0.0

dependency_overrides:
  # for dash_kit_control_panel and flutter_rollbar compatibility
  package_info: ^0.4.3

dev_dependencies:
  effective_dart: ^1.2.4
  flutter_launcher_icons:
    git:
      url: git://github.com/fluttercommunity/flutter_launcher_icons
      ref: flavors

  flutter_test:
    sdk: flutter

  build_runner: ^1.10.2
  freezed: ^0.11.6
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/
    - assets/images/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
