name: cash_flow
description: The best investment trainer!
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.9.0

  rxdart: ^0.24.0
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+1
  intl: ^0.16.1

  built_value: ^7.0.8
  built_collection: ^4.3.0
  freezed: ^0.10.6

  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.3+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.4+2
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.2
  apple_sign_in: ^0.1.0

  auto_size_text: ^2.1.0

  json_serializable: ^3.2.5

  flutter_svg: ^0.15.0

  url_launcher: ^5.4.2

  flutter_platform_core:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-platform-core
      ref: v0.0.18

  flutter_platform_network:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter_platform_network
      ref: v0.0.15

  flutter_platform_control_panel:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-platform-control-panel
      ref: v0.0.8

  flutter_platform_loadable:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-platform-loadable
      ref: v0.0.8

  uikit:
    git:
      url: git://github.com/mobile-dualbootpartners/flutter-ui-kit
      ref: v0.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  effective_dart: ^1.2.1

  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^7.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
