name: cash_flow
description: The best investment trainer!
version: 2.3.0+48

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  rxdart: ^0.26.0
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  uni_links: ^0.5.1
  crypto: 3.0.1
  get_it: ^6.1.1
  json_serializable: ^4.1.1
  device_preview: ^0.7.3
  purchases_flutter: ^3.0.0
  connectivity: ^3.0.3
  fimber: ^0.6.1
  #flutter_rollbar: ^0.0.2

  # Test
  mockito: ^5.0.7
  test: ^1.16.3

  # Immutability
  built_value: ^8.0.5
  built_collection: ^5.0.0
  freezed_annotation: ^0.14.1

  # Firebase
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_dynamic_links: ^2.0.2
  firebase_crashlytics: ^2.0.2
  firebase_auth: ^1.1.2
  firebase_database: ^7.0.0-dev.2
  firebase_messaging: ^9.1.3
  firebase_performance: ^0.7.0+2
  firebase_storage: ^8.0.5
  firebase_remote_config: ^0.10.0-dev.2
  cloud_firestore: ^1.0.7

  # Analytics
  amplitude_flutter: ^3.1.0

  # Notifications
  notification_permissions: ^0.5.0

  # Social
  flutter_facebook_auth: ^3.3.3+1
  google_sign_in: ^5.0.2
  sign_in_with_apple: ^3.1.0

  # Images
  image_picker: ^0.7.4
  image_cropper: ^1.4.0

  # UI
  flutter_hooks: ^0.16.0
  auto_size_text: ^3.0.0-nullsafety.0
  tutorial_coach_mark: ^1.0.0
  cached_network_image: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_svg: ^0.22.0
  #charts_flutter: ^0.10.0 #wait for Google update https://github.com/google/charts/issues/579#issuecomment-817792878
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  syncfusion_flutter_charts: ^19.1.63
  share: ^2.0.1
  flutter_swiper:
    git:
      url: https://github.com/Arkangel12/flutter_swiper
      ref: master
  k_chart:
    git:
      url: https://github.com/MrtnvM/k_chart
      ref: master
  shimmer: ^2.0.0
  app_settings: ^4.1.0
  #nnbd
  percent_indicator: ^3.3.0-nullsafety.1
  feedback: ^1.2.1

  # Dash Kit
  dash_kit_core: ^3.0.0-dev.5
  dash_kit_network: ^3.0.0-dev.3
  dash_kit_control_panel: ^3.0.0-dev.5
  dash_kit_loadable: ^3.0.0-dev.1
  dash_kit_uikit: ^3.0.0-dev.1

  version: ^2.0.0
  launch_review: ^3.0.1
  collection: ^1.15.0-nullsafety.4
  google_mobile_ads: ^0.12.1+1

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  built_value_generator:
    git:
      url: https://github.com/JEuler/built_value.dart.git
      path: built_value_generator
      ref: build-config-up

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/
    - assets/images/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
