// // Mocks generated by Mockito 5.0.7 from annotations
// // in cash_flow/test/services/purchase_service_test.dart.
// // Do not manually edit this file.

// import 'dart:async' as _i13;
// import 'dart:ui';

// import 'package:cash_flow/api_client/cash_flow_api_client.dart' as _i11;
// import 'package:cash_flow/models/domain/game/game_context/game_context.dart'
//     as _i17;
// import 'package:cash_flow/models/domain/game/quest/quest.dart' as _i15;
// import 'package:cash_flow/models/domain/room/room.dart' as _i5;
// import 'package:cash_flow/models/domain/user/online/online_profile.dart'
//     as _i20;
// import 'package:cash_flow/models/domain/user/purchase_profile.dart' as _i6;
// import 'package:cash_flow/models/domain/user/user_profile.dart' as _i7;
// import 'package:cash_flow/models/network/request/game/create_room_request_model.dart'
//     as _i18;
// import 'package:cash_flow/models/network/request/game/player_action_request_model.dart'
//     as _i16;
// import 'package:cash_flow/models/network/request/purchases/update_purchases_request_model.dart'
//     as _i19;
// import 'package:cash_flow/models/network/responses/game_template_response_model.dart'
//     as _i14;
// import 'package:cash_flow/models/network/responses/new_game_response_model.dart'
//     as _i4;
// import 'package:dash_kit_network/src/models/api_environment.dart' as _i2;
// import 'package:dash_kit_network/src/models/http_header.dart' as _i12;
// import 'package:dash_kit_network/src/models/response_mapper.dart' as _i21;
// import 'package:dash_kit_network/src/models/token_pair.dart' as _i23;
// import 'package:dio/src/dio.dart' as _i3;
// import 'package:dio/src/options.dart' as _i22;
// import 'package:flutter/material.dart';
// import 'package:in_app_purchase/in_app_purchase.dart';
// import 'package:in_app_purchase/src/billing_client_wrappers/sku_details_wrapper.dart'
//     as _i9;
// import 'package:in_app_purchase/src/in_app_purchase/in_app_purchase_connection.dart'
//     as _i24;
// import 'package:in_app_purchase/src/in_app_purchase/product_details.dart'
//     as _i8;
// import 'package:in_app_purchase/src/in_app_purchase/purchase_details.dart'
//     as _i10;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: comment_references
// // ignore_for_file: unnecessary_parenthesis

// // ignore_for_file: prefer_const_constructors

// // ignore_for_file: avoid_redundant_argument_values

// class _FakeApiEnvironment extends _i1.Fake implements _i2.ApiEnvironment {}

// class _FakeDio extends _i1.Fake implements _i3.Dio {}

// class _FakeNewGameResponseModel extends _i1.Fake
//     implements _i4.NewGameResponseModel {}

// class _FakeRoom extends _i1.Fake implements _i5.Room {}

// class _FakePurchaseProfile extends _i1.Fake implements _i6.PurchaseProfile {}

// class _FakeUserProfile extends _i1.Fake implements _i7.UserProfile {}

// class _FakeProductDetailsResponse extends _i1.Fake
//     implements _i8.ProductDetailsResponse {}

// @immutable
// class _FakeBillingResultWrapper extends _i1.Fake
//     implements _i9.BillingResultWrapper {
//   @override
//   bool operator ==(dynamic other) {
//     if (other.runtimeType != runtimeType) {
//       return false;
//     }

//     final BillingResultWrapper typedOther = other;
//     return typedOther is BillingResultWrapper &&
//         typedOther.responseCode == responseCode &&
//         typedOther.debugMessage == debugMessage;
//   }

//   @override
//   int get hashCode => hashValues(responseCode, debugMessage);
// }

// class _FakeQueryPurchaseDetailsResponse extends _i1.Fake
//     implements _i10.QueryPurchaseDetailsResponse {}

// class _FakePurchaseVerificationData extends _i1.Fake
//     implements _i10.PurchaseVerificationData {}

// class _FakeProductDetails extends _i1.Fake implements _i8.ProductDetails {}

// /// A class which mocks [CashFlowApiClient].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockCashFlowApiClient extends _i1.Mock implements _i11.CashFlowApiClient {
//   MockCashFlowApiClient() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i2.ApiEnvironment get environment =>
//       (super.noSuchMethod(Invocation.getter(#environment),
//           returnValue: _FakeApiEnvironment()) as _i2.ApiEnvironment);
//   @override
//   _i3.Dio get dio =>
//       (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio())
//           as _i3.Dio);
//   @override
//   List<_i12.HttpHeader> get commonHeaders =>
//       (super.noSuchMethod(Invocation.getter(#commonHeaders),
//           returnValue: <_i12.HttpHeader>[]) as List<_i12.HttpHeader>);
//   @override
//   _i13.Future<List<_i14.GameTemplateResponseModel>> getGameTemplates() =>
//       (super.noSuchMethod(Invocation.method(#getGameTemplates, []),
//               returnValue: Future<List<_i14.GameTemplateResponseModel>>.value(
//                   <_i14.GameTemplateResponseModel>[]))
//           as _i13.Future<List<_i14.GameTemplateResponseModel>>);
//   @override
//   _i13.Future<List<_i15.Quest>> getQuests(String? userId) =>
//       (super.noSuchMethod(Invocation.method(#getQuests, [userId]),
//               returnValue: Future<List<_i15.Quest>>.value(<_i15.Quest>[]))
//           as _i13.Future<List<_i15.Quest>>);
//   @override
//   _i13.Future<_i4.NewGameResponseModel> createNewGame(
//           {String? templateId, String? userId}) =>
//       (super.noSuchMethod(
//           Invocation.method(
//               #createNewGame, [], {#templateId: templateId, #userId: userId}),
//           returnValue: Future<_i4.NewGameResponseModel>.value(
//               _FakeNewGameResponseModel())) as _i13
//           .Future<_i4.NewGameResponseModel>);
//   @override
//   _i13.Future<_i4.NewGameResponseModel> createNewQuestGame(
//           {String? questId, String? userId}) =>
//       (super.noSuchMethod(
//           Invocation.method(
//               #createNewQuestGame, [], {#questId: questId, #userId: userId}),
//           returnValue: Future<_i4.NewGameResponseModel>.value(
//               _FakeNewGameResponseModel())) as _i13
//           .Future<_i4.NewGameResponseModel>);
//   @override
//   _i13.Future<void> sendPlayerAction(
//           _i16.PlayerActionRequestModel? playerAction) =>
//       (super.noSuchMethod(Invocation.method(#sendPlayerAction, [playerAction]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<void> startNewMonth(_i17.GameContext? gameContext) =>
//       (super.noSuchMethod(Invocation.method(#startNewMonth, [gameContext]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<_i5.Room> createRoom(_i18.CreateRoomRequestModel? requestModel) =>
//       (super.noSuchMethod(Invocation.method(#createRoom, [requestModel]),
//               returnValue: Future<_i5.Room>.value(_FakeRoom()))
//           as _i13.Future<_i5.Room>);
//   @override
//   _i13.Future<void> setRoomParticipantReady(
//           String? roomId, String? participantId) =>
//       (super.noSuchMethod(
//           Invocation.method(#setRoomParticipantReady, [roomId, participantId]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<void> createRoomGame(String? roomId) =>
//       (super.noSuchMethod(Invocation.method(#createRoomGame, [roomId]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<_i6.PurchaseProfile> sendPurchasedProducts(
//           _i19.UpdatePurchasesRequestModel? updatedPurchases) =>
//       (super.noSuchMethod(
//               Invocation.method(#sendPurchasedProducts, [updatedPurchases]),
//               returnValue:
//                   Future<_i6.PurchaseProfile>.value(_FakePurchaseProfile()))
//           as _i13.Future<_i6.PurchaseProfile>);
//   @override
//   _i13.Future<_i7.UserProfile> getUserProfile(String? userId) =>
//       (super.noSuchMethod(Invocation.method(#getUserProfile, [userId]),
//               returnValue: Future<_i7.UserProfile>.value(_FakeUserProfile()))
//           as _i13.Future<_i7.UserProfile>);
//   @override
//   _i13.Future<void> setOnlineStatus(_i20.OnlineProfile? user) =>
//       (super.noSuchMethod(Invocation.method(#setOnlineStatus, [user]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<List<_i20.OnlineProfile>> getOnlineProfiles(String? id) =>
//       (super.noSuchMethod(Invocation.method(#getOnlineProfiles, [id]),
//               returnValue: Future<List<_i20.OnlineProfile>>.value(
//                   <_i20.OnlineProfile>[]))
//           as _i13.Future<List<_i20.OnlineProfile>>);
//   @override
//   _i13.Future<void> addFriends(
//           String? userId, List<String>? usersAddToFriends) =>
//       (super.noSuchMethod(
//           Invocation.method(#addFriends, [userId, usersAddToFriends]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<void> removeFromFriends(
//           {String? userId, String? removedFriendId}) =>
//       (super.noSuchMethod(
//           Invocation.method(#removeFromFriends, [],
//               {#userId: userId, #removedFriendId: removedFriendId}),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<T> get<T>(
//           {String? path,
//           _i21.ResponseMapper<T>? responseMapper,
//           bool? isAuthorisedRequest,
//           bool? validate,
//           Map<String, dynamic>? queryParams = const {},
//           List<_i12.HttpHeader>? headers = const [],
//           int? connectTimeout,
//           int? receiveTimeout,
//           int? sendTimeout}) =>
//       (super.noSuchMethod(
//           Invocation.method(#get, [], {
//             #path: path,
//             #responseMapper: responseMapper,
//             #isAuthorisedRequest: isAuthorisedRequest,
//             #validate: validate,
//             #queryParams: queryParams,
//             #headers: headers,
//             #connectTimeout: connectTimeout,
//             #receiveTimeout: receiveTimeout,
//             #sendTimeout: sendTimeout
//           }),
//           returnValue: Future<T>.value(null)) as _i13.Future<T>);
//   @override
//   _i13.Future<T> post<T>(
//           {String? path,
//           _i21.ResponseMapper<T>? responseMapper,
//           List<_i12.HttpHeader>? headers = const [],
//           _i22.ResponseType? responseType = _i22.ResponseType.json,
//           dynamic body,
//           bool? isAuthorisedRequest,
//           bool? validate,
//           int? connectTimeout,
//           int? receiveTimeout,
//           int? sendTimeout}) =>
//       (super.noSuchMethod(
//           Invocation.method(#post, [], {
//             #path: path,
//             #responseMapper: responseMapper,
//             #headers: headers,
//             #responseType: responseType,
//             #body: body,
//             #isAuthorisedRequest: isAuthorisedRequest,
//             #validate: validate,
//             #connectTimeout: connectTimeout,
//             #receiveTimeout: receiveTimeout,
//             #sendTimeout: sendTimeout
//           }),
//           returnValue: Future<T>.value(null)) as _i13.Future<T>);
//   @override
//   _i13.Future<T> put<T>(
//           {String? path,
//           _i21.ResponseMapper<T>? responseMapper,
//           List<_i12.HttpHeader>? headers = const [],
//           _i22.ResponseType? responseType = _i22.ResponseType.json,
//           dynamic body,
//           bool? isAuthorisedRequest,
//           bool? validate,
//           int? connectTimeout,
//           int? receiveTimeout,
//           int? sendTimeout}) =>
//       (super.noSuchMethod(
//           Invocation.method(#put, [], {
//             #path: path,
//             #responseMapper: responseMapper,
//             #headers: headers,
//             #responseType: responseType,
//             #body: body,
//             #isAuthorisedRequest: isAuthorisedRequest,
//             #validate: validate,
//             #connectTimeout: connectTimeout,
//             #receiveTimeout: receiveTimeout,
//             #sendTimeout: sendTimeout
//           }),
//           returnValue: Future<T>.value(null)) as _i13.Future<T>);
//   @override
//   _i13.Future<T> patch<T>(
//           {String? path,
//           _i21.ResponseMapper<T>? responseMapper,
//           List<_i12.HttpHeader>? headers = const [],
//           _i22.ResponseType? responseType = _i22.ResponseType.json,
//           dynamic body,
//           bool? isAuthorisedRequest,
//           bool? validate,
//           int? connectTimeout,
//           int? receiveTimeout,
//           int? sendTimeout}) =>
//       (super.noSuchMethod(
//           Invocation.method(#patch, [], {
//             #path: path,
//             #responseMapper: responseMapper,
//             #headers: headers,
//             #responseType: responseType,
//             #body: body,
//             #isAuthorisedRequest: isAuthorisedRequest,
//             #validate: validate,
//             #connectTimeout: connectTimeout,
//             #receiveTimeout: receiveTimeout,
//             #sendTimeout: sendTimeout
//           }),
//           returnValue: Future<T>.value(null)) as _i13.Future<T>);
//   @override
//   _i13.Future<T> delete<T>(
//           {String? path,
//           _i21.ResponseMapper<T>? responseMapper,
//           List<_i12.HttpHeader>? headers = const [],
//           dynamic body,
//           bool? isAuthorisedRequest,
//           bool? validate,
//           int? connectTimeout,
//           int? receiveTimeout,
//           int? sendTimeout}) =>
//       (super.noSuchMethod(
//           Invocation.method(#delete, [], {
//             #path: path,
//             #responseMapper: responseMapper,
//             #headers: headers,
//             #body: body,
//             #isAuthorisedRequest: isAuthorisedRequest,
//             #validate: validate,
//             #connectTimeout: connectTimeout,
//             #receiveTimeout: receiveTimeout,
//             #sendTimeout: sendTimeout
//           }),
//           returnValue: Future<T>.value(null)) as _i13.Future<T>);
//   @override
//   _i13.Future<void> updateAuthTokens(_i23.TokenPair? tokenPair) =>
//       (super.noSuchMethod(Invocation.method(#updateAuthTokens, [tokenPair]),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<void> clearAuthTokens() =>
//       (super.noSuchMethod(Invocation.method(#clearAuthTokens, []),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
//   @override
//   _i13.Future<bool> isAuthorised() =>
//       (super.noSuchMethod(Invocation.method(#isAuthorised, []),
//           returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
// }

// /// A class which mocks [InAppPurchaseConnection].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockInAppPurchaseConnection extends _i1.Mock
//     implements _i24.InAppPurchaseConnection {
//   MockInAppPurchaseConnection() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i13.Stream<List<_i10.PurchaseDetails>> get purchaseUpdatedStream =>
//       (super.noSuchMethod(Invocation.getter(#purchaseUpdatedStream),
//               returnValue: Stream<List<_i10.PurchaseDetails>>.empty())
//           as _i13.Stream<List<_i10.PurchaseDetails>>);
//   @override
//   _i13.Future<bool> isAvailable() =>
//       (super.noSuchMethod(Invocation.method(#isAvailable, []),
//           returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
//   @override
//   _i13.Future<_i8.ProductDetailsResponse> queryProductDetails(
//           Set<String>? identifiers) =>
//       (super.noSuchMethod(
//               Invocation.method(#queryProductDetails, [identifiers]),
//               returnValue: Future<_i8.ProductDetailsResponse>.value(
//                   _FakeProductDetailsResponse()))
//           as _i13.Future<_i8.ProductDetailsResponse>);
//   @override
//   _i13.Future<bool> buyNonConsumable({_i10.PurchaseParam? purchaseParam}) =>
//       (super.noSuchMethod(
//           Invocation.method(
//               #buyNonConsumable, [], {#purchaseParam: purchaseParam}),
//           returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
//   @override
//   _i13.Future<bool> buyConsumable(
//           {_i10.PurchaseParam? purchaseParam, bool? autoConsume = true}) =>
//       (super.noSuchMethod(
//           Invocation.method(#buyConsumable, [],
//               {#purchaseParam: purchaseParam, #autoConsume: autoConsume}),
//           returnValue: Future<bool>.value(false)) as _i13.Future<bool>);
//   @override
//   _i13.Future<_i9.BillingResultWrapper> completePurchase(
//           _i10.PurchaseDetails? purchase) =>
//       (super.noSuchMethod(Invocation.method(#completePurchase, [purchase]),
//               returnValue: Future<_i9.BillingResultWrapper>.value(
//                   _FakeBillingResultWrapper()))
//           as _i13.Future<_i9.BillingResultWrapper>);
//   @override
//   _i13.Future<_i9.BillingResultWrapper> consumePurchase(
//           _i10.PurchaseDetails? purchase) =>
//       (super.noSuchMethod(Invocation.method(#consumePurchase, [purchase]),
//               returnValue: Future<_i9.BillingResultWrapper>.value(
//                   _FakeBillingResultWrapper()))
//           as _i13.Future<_i9.BillingResultWrapper>);
//   @override
//   _i13.Future<_i10.QueryPurchaseDetailsResponse> queryPastPurchases(
//           {String? applicationUserName}) =>
//       (super.noSuchMethod(
//               Invocation.method(#queryPastPurchases, [],
//                   {#applicationUserName: applicationUserName}),
//               returnValue: Future<_i10.QueryPurchaseDetailsResponse>.value(
//                   _FakeQueryPurchaseDetailsResponse()))
//           as _i13.Future<_i10.QueryPurchaseDetailsResponse>);
//   @override
//   _i13.Future<_i10.PurchaseVerificationData?>
//       refreshPurchaseVerificationData() => (super.noSuchMethod(
//               Invocation.method(#refreshPurchaseVerificationData, []),
//               returnValue: Future<_i10.PurchaseVerificationData?>.value(
//                   _FakePurchaseVerificationData()))
//           as _i13.Future<_i10.PurchaseVerificationData?>);
//   @override
//   _i13.Future<void> presentCodeRedemptionSheet() =>
//       (super.noSuchMethod(Invocation.method(#presentCodeRedemptionSheet, []),
//           returnValue: Future<void>.value(null),
//           returnValueForMissingStub: Future.value()) as _i13.Future<void>);
// }

// /// A class which mocks [PurchaseParam].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockPurchaseParam extends _i1.Mock implements _i10.PurchaseParam {
//   MockPurchaseParam() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i8.ProductDetails get productDetails =>
//       (super.noSuchMethod(Invocation.getter(#productDetails),
//           returnValue: _FakeProductDetails()) as _i8.ProductDetails);
//   @override
//   bool get sandboxTesting => (super
//           .noSuchMethod(Invocation.getter(#sandboxTesting), returnValue: false)
//       as bool);
//   @override
//   bool get simulatesAskToBuyInSandbox =>
//       (super.noSuchMethod(Invocation.getter(#simulatesAskToBuyInSandbox),
//           returnValue: false) as bool);
// }
